/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Detalle;
import ec.edu.ups.modelo.Estante;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Producto;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Eduardo Ayora
 */
public class Prueba extends javax.swing.JFrame {

    ControladorProducto controladorProducto;
    ControladorCliente controladorCliente;
    Estante estante1;
    Estante estante2;
    List<Factura> facturas;
    Cliente cliente;

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        setLocationRelativeTo(null);
        facturas = new ArrayList<>();
        controladorProducto = new ControladorProducto();
        controladorCliente = new ControladorCliente();
        estante1 = new Estante();
        estante2 = new Estante();
        estante1.setCodigo(1);
        estante1.setProducto(controladorProducto.read(1));
        estante2.setCodigo(2);
        estante2.setProducto(controladorProducto.read(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdu = new javax.swing.JButton();
        btnKaren = new javax.swing.JButton();
        btnP1 = new javax.swing.JButton();
        btnP11 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP22 = new javax.swing.JButton();
        btnCaja1 = new javax.swing.JToggleButton();
        btnCaja2 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCerrar1 = new javax.swing.JButton();
        btnCerrar2 = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEdu.setText("Edu");
        btnEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEduActionPerformed(evt);
            }
        });

        btnKaren.setText("Karen");
        btnKaren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKarenActionPerformed(evt);
            }
        });

        btnP1.setText("Producto 1");
        btnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP1ActionPerformed(evt);
            }
        });

        btnP11.setText("Producto 1");
        btnP11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP11ActionPerformed(evt);
            }
        });

        btnP2.setText("Producto 2");
        btnP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2ActionPerformed(evt);
            }
        });

        btnP22.setText("Producto 2");
        btnP22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP22ActionPerformed(evt);
            }
        });

        btnCaja1.setText("Estante1");
        btnCaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja1ActionPerformed(evt);
            }
        });

        btnCaja2.setText("Estante2");
        btnCaja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja2ActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCerrar1.setText("Cerrar1");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        btnCerrar2.setText("Cerrar2");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        btnFactura.setText("Crear Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCaja1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addComponent(btnP1)
                                .addGap(30, 30, 30)
                                .addComponent(btnP11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCaja2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnP2)
                                .addGap(30, 30, 30)
                                .addComponent(btnP22)))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrar1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdu)
                                .addGap(109, 109, 109)
                                .addComponent(btnKaren))
                            .addComponent(btnCerrar2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnFactura)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdu)
                    .addComponent(btnKaren))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnP1)
                    .addComponent(btnP11)
                    .addComponent(btnCaja1)
                    .addComponent(btnCerrar1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnP2)
                    .addComponent(btnP22)
                    .addComponent(btnCaja2)
                    .addComponent(btnCerrar2))
                .addGap(40, 40, 40)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnFactura)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEduActionPerformed
        // TODO add your handling code here:
        System.out.println("Edu esta usando la tarjeta");
        String usuario = "0101010101";
        cliente = controladorCliente.findByCedula(usuario);
    }//GEN-LAST:event_btnEduActionPerformed

    private void btnKarenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKarenActionPerformed
        // TODO add your handling code here:
        System.out.println("Karen esta usando la tarjeta");
        String usuario = "0202020202";
        cliente = controladorCliente.findByCedula(usuario);
    }//GEN-LAST:event_btnKarenActionPerformed

    private void btnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1ActionPerformed
        // TODO add your handling code here:
        Cliente clienteEstante = estante1.getCliente();
        if (clienteEstante != null) {
            Producto producto = estante1.getProducto();
            System.out.println(clienteEstante);
            facturacion(clienteEstante, producto);
        }
    }//GEN-LAST:event_btnP1ActionPerformed

    private void btnP22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP22ActionPerformed
        // TODO add your handling code here:
        Cliente clienteEstante = estante2.getCliente();
        if (clienteEstante != null) {
            Producto producto = estante2.getProducto();
            System.out.println(clienteEstante);
            facturacion(clienteEstante, producto);
        }
    }//GEN-LAST:event_btnP22ActionPerformed

    private void btnP11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP11ActionPerformed
        // TODO add your handling code here:
        Cliente clienteEstante = estante1.getCliente();
        if (clienteEstante != null) {
            Producto producto = estante1.getProducto();
            System.out.println(clienteEstante);
            facturacion(clienteEstante, producto);
        }
    }//GEN-LAST:event_btnP11ActionPerformed

    private void btnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2ActionPerformed
        // TODO add your handling code here:
        Cliente clienteEstante = estante2.getCliente();
        if (clienteEstante != null) {
            Producto producto = estante2.getProducto();
            System.out.println(clienteEstante);
            facturacion(clienteEstante, producto);
        }
    }//GEN-LAST:event_btnP2ActionPerformed

    private void btnCaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja1ActionPerformed
        // TODO add your handling code here:
        if (cliente != null) {
            if (estante1.isAbierto() == false){
                estante1.setAbierto(true);
                estante1.setCliente(cliente);
            }
        }
    }//GEN-LAST:event_btnCaja1ActionPerformed

    private void btnCaja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja2ActionPerformed
        // TODO add your handling code here:
        if (cliente != null) {
            if (estante2.isAbierto() == false) {
                estante2.setAbierto(true);
                estante2.setCliente(cliente);
            }
        }
    }//GEN-LAST:event_btnCaja2ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        cliente = null;
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        for(Factura factura : facturas) {
            double subtotal = 0;
            for(Detalle detalle : factura.getDetalles()) {
                subtotal += detalle.getSubtotal();
            }
            factura.setSubtotal(subtotal);
            factura.setIva(factura.getSubtotal() * 0.12);
            factura.setTotal(factura.getSubtotal() + factura.getIva());
            System.out.println(factura);
        }
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        // TODO add your handling code here:
        estante1.setAbierto(false);
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        // TODO add your handling code here:
        estante2.setAbierto(false);
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    public void facturacion(Cliente clienteEstante, Producto producto) {
        boolean clienteEncontrado = false;
        for (Factura factura : facturas) {
            if (factura.getCliente().equals(clienteEstante)) {
                System.out.println("Cliente encontrado");
                boolean productoEncontrado = false;
                for (Detalle detalle : factura.getDetalles()) {
                    if (detalle.getProducto().equals(producto)) {
                        System.out.println("Producto encontrado");
                        detalle.setCantidad(detalle.getCantidad() + 1);
                        detalle.setSubtotal(detalle.getCantidad() * detalle.getPrecio());
                        productoEncontrado = true;
                    }
                }
                if (productoEncontrado == false) {
                    Detalle detalle = new Detalle();
                    detalle.setPrecio(producto.getPrecio());
                    detalle.setCantidad(1);
                    detalle.setSubtotal(producto.getPrecio());
                    detalle.setProducto(producto);
                    factura.getDetalles().add(detalle);
                }
                clienteEncontrado = true;
                break;
            }
        }
        if (clienteEncontrado == false) {
            Detalle detalle = new Detalle();
            detalle.setPrecio(producto.getPrecio());
            detalle.setCantidad(1);
            detalle.setSubtotal(producto.getPrecio());
            detalle.setProducto(producto);
            Factura factura = new Factura();
            factura.setCliente(clienteEstante);
            factura.getDetalles().add(detalle);
            facturas.add(factura);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JToggleButton btnCaja1;
    private javax.swing.JButton btnCaja2;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btnEdu;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnKaren;
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP11;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton btnP22;
    // End of variables declaration//GEN-END:variables
}
