/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorDetalle;
import ec.edu.ups.controlador.ControladorEstante;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorPin;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Detalle;
import ec.edu.ups.modelo.Estante;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Pin;
import ec.edu.ups.modelo.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.postgresql.util.PSQLException;

/**
 *
 * @author Eduardo Ayora
 */
public class Prueba extends javax.swing.JFrame {

    ControladorProducto controladorProducto;
    ControladorCliente controladorCliente;
    ControladorFactura controladorFactura;
    ControladorDetalle controladorDetalle;
    List<Pin> pines;
    List<Estante> estantes;
    List<Factura> facturas;
    Cliente cliente;

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        System.out.println(System.currentTimeMillis());
        initComponents();
        setLocationRelativeTo(null);
        facturas = new ArrayList<>();
        controladorProducto = new ControladorProducto();
        controladorCliente = new ControladorCliente();
        controladorFactura = new ControladorFactura();
        controladorDetalle = new ControladorDetalle();
        pines = new ControladorPin().listar();
        estantes = new ControladorEstante().listar();
        emparejarPinesEstantes();
        iniciarTimer();
    }
    
    public void emparejarPinesEstantes(){
        for(Pin pin : pines){
            for(Estante estante : estantes){
                if(pin.getEstante().getCodigo() == estante.getCodigo()){
                    pin.setEstante(estante);
                }
            }
        }
    }

    public void iniciarTimer() {
        Timer timer = new Timer(8000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.out.println("Revisando");
                generarFactura();
            }
        });
        timer.start();
    }

    public void llegoPinArduino(int datoArduino) {
        Cliente clienteEstante = pines.get(datoArduino - 1).getEstante().getCliente();
        if (clienteEstante != null && pines.get(datoArduino - 1).getEstante().isAbierto() && pines.get(datoArduino - 1).isActivado() == false) {
            Producto producto = pines.get(datoArduino - 1).getEstante().getProducto();
            System.out.println(clienteEstante);
            facturacion(clienteEstante, producto);
            pines.get(datoArduino - 1).setActivado(true);
        }
    }

    public void llegoTarjetaArduino(String usuario) {
        cliente = controladorCliente.findByCedula(usuario);
        System.out.println(cliente);
    }

    public void estanteSeleccionado(int estante) {
        if (cliente != null) {
            if (estantes.get(estante - 1).isAbierto() == false) {
                System.out.println("No esta abierto estante, se ha seleccionado");
                estantes.get(estante - 1).setSeleccionado(true);
                estantes.get(estante - 1).setCliente(cliente);
            } else {
                System.out.println("No puede seleccionar");
            }
        }
    }
    
    public void cerrarEstante(int codigoArduino){
        estantes.get(codigoArduino - 1).setAbierto(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdu = new javax.swing.JButton();
        btnKaren = new javax.swing.JButton();
        btnP1 = new javax.swing.JButton();
        btnP11 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP22 = new javax.swing.JButton();
        btnCaja1 = new javax.swing.JToggleButton();
        btnCaja2 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCerrar1 = new javax.swing.JButton();
        btnCerrar2 = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEdu.setText("Edu");
        btnEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEduActionPerformed(evt);
            }
        });

        btnKaren.setText("Karen");
        btnKaren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKarenActionPerformed(evt);
            }
        });

        btnP1.setText("Producto 1");
        btnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP1ActionPerformed(evt);
            }
        });

        btnP11.setText("Producto 1");
        btnP11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP11ActionPerformed(evt);
            }
        });

        btnP2.setText("Producto 2");
        btnP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2ActionPerformed(evt);
            }
        });

        btnP22.setText("Producto 2");
        btnP22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP22ActionPerformed(evt);
            }
        });

        btnCaja1.setText("Estante1");
        btnCaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja1ActionPerformed(evt);
            }
        });

        btnCaja2.setText("Estante2");
        btnCaja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja2ActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCerrar1.setText("Cerrar1");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        btnCerrar2.setText("Cerrar2");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        btnFactura.setText("Crear Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(172, 172, 172)
                        .addComponent(btnFactura)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCaja1)
                            .addComponent(btnCaja2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrar1)
                            .addComponent(btnCerrar2))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnP1)
                                .addGap(30, 30, 30)
                                .addComponent(btnP11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnP2)
                                .addGap(30, 30, 30)
                                .addComponent(btnP22)))))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKaren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnEdu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKaren)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnP1)
                    .addComponent(btnP11)
                    .addComponent(btnCaja1)
                    .addComponent(btnCerrar1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnP2)
                    .addComponent(btnP22)
                    .addComponent(btnCaja2)
                    .addComponent(btnCerrar2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnFactura))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEduActionPerformed
        // TODO add your handling code here:
        System.out.println("Edu esta usando la tarjeta");
        String usuario = "0101010101";
        llegoTarjetaArduino(usuario);
    }//GEN-LAST:event_btnEduActionPerformed

    private void btnKarenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKarenActionPerformed
        // TODO add your handling code here:
        System.out.println("Karen esta usando la tarjeta");
        String usuario = "0202020202";
        llegoTarjetaArduino(usuario);
    }//GEN-LAST:event_btnKarenActionPerformed

    private void btnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1ActionPerformed
        // TODO add your handling code here:
        int datoArduino = 1;
        llegoPinArduino(datoArduino);
    }//GEN-LAST:event_btnP1ActionPerformed

    private void btnP22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP22ActionPerformed
        // TODO add your handling code here:
        int datoArduino = 4;
        llegoPinArduino(datoArduino);
    }//GEN-LAST:event_btnP22ActionPerformed

    private void btnP11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP11ActionPerformed
        // TODO add your handling code here:
        int datoArduino = 2;
        llegoPinArduino(datoArduino);
    }//GEN-LAST:event_btnP11ActionPerformed

    private void btnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2ActionPerformed
        // TODO add your handling code here:
        int datoArduino = 3;
        llegoPinArduino(datoArduino);
    }//GEN-LAST:event_btnP2ActionPerformed

    private void btnCaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja1ActionPerformed
        // TODO add your handling code here:
        int estante = 1;
        estanteSeleccionado(estante);
        btnCaja1.setSelected(false);
    }//GEN-LAST:event_btnCaja1ActionPerformed

    private void btnCaja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja2ActionPerformed
        // TODO add your handling code here:
        int estante = 2;
        estanteSeleccionado(estante);
    }//GEN-LAST:event_btnCaja2ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        cliente = null;
        int contador = 1;
        for (Estante estante : estantes) {
            if (estante.isSeleccionado()) {
                System.out.println("Esta seleccionado estante " + contador);
                estante.setAbierto(true);
                estante.setSeleccionado(false);
            }
            contador++;
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        for (Factura factura : facturas) {
            factura.setNumeroFactura(controladorFactura.getCodigo());
            double subtotal = 0;
            for (Detalle detalle : factura.getDetalles()) {
                subtotal += detalle.getSubtotal();
            }
            factura.setSubtotal(subtotal);
            factura.setIva(factura.getSubtotal() * 0.12);
            factura.setTotal(factura.getSubtotal() + factura.getIva());
            try {
                controladorFactura.create(factura);
                JOptionPane.showMessageDialog(null, "Factura creada");
            } catch (PSQLException ex) {
                ex.printStackTrace();
            }
            for (Detalle detalle : factura.getDetalles()) {
                try {
                    controladorDetalle.create(detalle, factura.getNumeroFactura());
                } catch (PSQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        facturas = new ArrayList<>();
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        // TODO add your handling code here:
        int codigoArduino = 1;
        cerrarEstante(codigoArduino);
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        // TODO add your handling code here:
        int codigoArduino = 2;
        cerrarEstante(codigoArduino);
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    
    
    public void facturacion(Cliente clienteEstante, Producto producto) {
        boolean clienteEncontrado = false;
        for (Factura factura : facturas) {
            if (factura.getCliente().equals(clienteEstante)) {
                System.out.println("Cliente encontrado");
                boolean productoEncontrado = false;
                for (Detalle detalle : factura.getDetalles()) {
                    if (detalle.getProducto().equals(producto)) {
                        System.out.println("Producto encontrado");
                        detalle.setCantidad(detalle.getCantidad() + 1);
                        detalle.setSubtotal(detalle.getCantidad() * detalle.getPrecio());
                        productoEncontrado = true;
                    }
                }
                if (productoEncontrado == false) {
                    Detalle detalle = new Detalle();
                    detalle.setPrecio(producto.getPrecio());
                    detalle.setCantidad(1);
                    detalle.setSubtotal(producto.getPrecio());
                    detalle.setProducto(producto);
                    factura.getDetalles().add(detalle);
                }
                clienteEncontrado = true;
                factura.setTiempoEspera(System.currentTimeMillis());
                break;
            }
        }
        if (clienteEncontrado == false) {
            Detalle detalle = new Detalle();
            detalle.setPrecio(producto.getPrecio());
            detalle.setCantidad(1);
            detalle.setSubtotal(producto.getPrecio());
            detalle.setProducto(producto);
            Factura factura = new Factura();
            factura.setCliente(clienteEstante);
            factura.getDetalles().add(detalle);
            facturas.add(factura);
        }

    }

    public void generarFactura() {
        for (int i = 0; i < facturas.size(); i++) {
            Factura factura = facturas.get(i);
            System.out.println(System.currentTimeMillis() - factura.getTiempoEspera());
            if (System.currentTimeMillis() - factura.getTiempoEspera() > 17000) {
                factura.setNumeroFactura(controladorFactura.getCodigo());
                double subtotal = 0;
                for (Detalle detalle : factura.getDetalles()) {
                    subtotal += detalle.getSubtotal();
                }
                factura.setSubtotal(subtotal);
                factura.setIva(factura.getSubtotal() * 0.12);
                factura.setTotal(factura.getSubtotal() + factura.getIva());
                try {
                    controladorFactura.create(factura);
                    JOptionPane.showMessageDialog(null, "Factura creada");
                } catch (PSQLException ex) {
                    ex.printStackTrace();
                }
                for (Detalle detalle : factura.getDetalles()) {
                    try {
                        controladorDetalle.create(detalle, factura.getNumeroFactura());
                    } catch (PSQLException ex) {
                        ex.printStackTrace();
                    }
                }
                facturas.remove(i);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JToggleButton btnCaja1;
    private javax.swing.JButton btnCaja2;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btnEdu;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnKaren;
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP11;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton btnP22;
    // End of variables declaration//GEN-END:variables
}
