/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.vista.persona.VistaActualizarPersona;
import ec.edu.ups.vista.persona.VistaCrearPersona;
import ec.edu.ups.vista.persona.VistaListarPersonas;
import ec.edu.ups.vista.persona.VistaLeerPersona;
import ec.edu.ups.vista.persona.VistaEliminarPersona;
import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;


/**
 *
 * @author Eduardo Ayora
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VistaCrearPersona crear;
    private VistaLeerPersona leer;
    private VistaEliminarPersona eliminar;
    private VistaActualizarPersona actualizar;
    private VistaListarPersonas listarPersonas;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itmCrear = new javax.swing.JMenuItem();
        itmLeer = new javax.swing.JMenuItem();
        itmActualizar = new javax.swing.JMenuItem();
        itmEliminar = new javax.swing.JMenuItem();
        itmListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Persona");

        itmCrear.setMnemonic('o');
        itmCrear.setText("Crear");
        itmCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCrearActionPerformed(evt);
            }
        });
        fileMenu.add(itmCrear);

        itmLeer.setMnemonic('s');
        itmLeer.setText("Leer");
        itmLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLeerActionPerformed(evt);
            }
        });
        fileMenu.add(itmLeer);

        itmActualizar.setMnemonic('a');
        itmActualizar.setText("Actualizar");
        itmActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmActualizarActionPerformed(evt);
            }
        });
        fileMenu.add(itmActualizar);

        itmEliminar.setMnemonic('x');
        itmEliminar.setText("Eliminar");
        itmEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEliminarActionPerformed(evt);
            }
        });
        fileMenu.add(itmEliminar);

        itmListar.setText("Listar");
        itmListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarActionPerformed(evt);
            }
        });
        fileMenu.add(itmListar);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEliminarActionPerformed

        if (eliminar == null || eliminar.isVisible() == false) {
            eliminar = new VistaEliminarPersona();
            eliminar.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = eliminar.getSize();
            eliminar.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(eliminar);
        }
    }//GEN-LAST:event_itmEliminarActionPerformed

    private void itmCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCrearActionPerformed
        // TODO add your handling code here:
        if (crear == null || crear.isVisible() == false) {
            crear = new VistaCrearPersona();
            crear.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = crear.getSize();
            crear.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(crear);
        }
    }//GEN-LAST:event_itmCrearActionPerformed

    private void itmLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLeerActionPerformed

        if (leer == null || leer.isVisible() == false) {
            leer = new VistaLeerPersona();
            leer.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = leer.getSize();
            leer.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(leer);
        }
    }//GEN-LAST:event_itmLeerActionPerformed

    private void itmActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmActualizarActionPerformed
        // TODO add your handling code here:
        if (actualizar == null || actualizar.isVisible() == false) {
            actualizar = new VistaActualizarPersona();
            actualizar.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = actualizar.getSize();
            actualizar.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(actualizar);
        }
    }//GEN-LAST:event_itmActualizarActionPerformed

    private void itmListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarActionPerformed
        // TODO add your handling code here:
        if (listarPersonas == null || listarPersonas.isVisible() == false) {
            listarPersonas = new VistaListarPersonas();
            listarPersonas.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = listarPersonas.getSize();
            listarPersonas.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(listarPersonas);
        }
    }//GEN-LAST:event_itmListarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itmActualizar;
    private javax.swing.JMenuItem itmCrear;
    private javax.swing.JMenuItem itmEliminar;
    private javax.swing.JMenuItem itmLeer;
    private javax.swing.JMenuItem itmListar;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
