/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author DELL
 */
public class VistaCliente extends javax.swing.JFrame {

    private List<JButton> botones;

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        botones = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pane.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(pane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public void agregarBotones() {
        Font fuente = new Font("arial", Font.PLAIN, 35);
        for (int i = 0; i < controladorMesa.getLista().size(); i++) {
            if (controladorMesa.getLista().get(i).isMesaAbierta()) {
                JButton btn = new JButton(mensajes.getString("txt.mesa") + " "
                        + Integer.toString(controladorMesa.getLista().get(i).getNumeroMesa()));
                btn.setName(Integer.toString(i));
                btn.setFont(fuente);
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        String texto = btn.getName();
                        int numero = Integer.parseInt(texto);
                        Mesa mesa = controladorMesa.getLista().get(numero);
                        mesa.setMesaAbierta(false);
                        mesero.getMesas().add(mesa);
                        mesa.setMesero(mesero);
                        VentanaPrincipal.usuarioMesero.vistaMesero = new VistaMesero(mesero, controladorMesa, controladorProducto, mensajes);
                        VentanaPrincipal.usuarioMesero.vistaMesero.setVisible(true);
                        dispose();
                    }
                });
                pane.add(btn);
                botones.add(btn);
            }
        }
        pane.updateUI();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
}
