/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.ClaveAdmin;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Producto;
import ec.edu.ups.modelo.Render;
import ec.edu.ups.vista.persona.VistaActualizarPersona;
import ec.edu.ups.vista.persona.VistaCrearPersona;
import ec.edu.ups.vista.persona.VistaListarPersonas;
import ec.edu.ups.vista.persona.VistaLeerPersona;
import ec.edu.ups.vista.persona.VistaEliminarPersona;
import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.postgresql.util.PSQLException;

/**
 *
 * @author Eduardo Ayora
 */
public class VistaAdmin extends javax.swing.JFrame {

    private CambioContrasenia cambioContrasenia;
    private ClaveAdmin claveAdmin;
    private ControladorFactura controladorFactura;
    private ControladorCliente controladorCliente;
    private ControladorProducto controladorProducto;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaAdmin() {
        initComponents();
        controladorFactura = new ControladorFactura();
        controladorCliente = new ControladorCliente();
        controladorProducto = new ControladorProducto();
        claveAdmin = new ClaveAdmin();
        this.setExtendedState(MAXIMIZED_BOTH);
        tabFactura.setRowHeight(40);
        tabProducto.setRowHeight(40);
        tabCliente.setRowHeight(40);
        llenarDatosFactura();
        llenarDatosProducto();
        llenarDatosCliente();
    }

    public void llenarDatosFactura() {
        tabFactura.setDefaultRenderer(Object.class, new Render());
        JButton btnVer = new JButton("Ver");
        DefaultTableModel modelo = (DefaultTableModel) tabFactura.getModel();
        vaciarTablaFactura(modelo);
        List<Factura> lista = controladorFactura.listar();
        for (Factura factura : lista) {
            Object[] datos = {factura.getNumeroFactura(),
                factura.getFecha(),
                factura.getCliente().getNombre(),
                factura.getTotal(),
                factura.isActivo(),
                btnVer
            };
            modelo.addRow(datos);
        }

    }
    
    public void llenarDatosProducto(){
        DefaultTableModel modelo = (DefaultTableModel) tabProducto.getModel();
        vaciarTablaProducto(modelo);
        List<Producto> lista = controladorProducto.listar();
        for (Producto producto : lista) {
            Object[] datos = {producto.getCodigoProducto(),
                producto.getNombre(),
                producto.getPrecio(),
                producto.getDescripcion()
            };
            modelo.addRow(datos);
        }
    }
    
    public void llenarDatosCliente(){
        DefaultTableModel modelo = (DefaultTableModel) tabCliente.getModel();
        vaciarTablaCliente(modelo);
        List<Cliente> lista = controladorCliente.listar();
        for (Cliente cliente : lista) {
            Object[] datos = {cliente.getCedula(),
                cliente.getNombre() + " " + cliente.getApellido(),
                cliente.getCelular(),
                cliente.getCorreo(),
                cliente.getDireccion(),
                cliente.getCodigoTarjeta()
            };
            modelo.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestaFactura = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFactura = new javax.swing.JTable();
        bBuscarFac = new javax.swing.JButton();
        tNumFactura = new javax.swing.JTextField();
        lNumFactura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProducto = new javax.swing.JTable();
        lCodProducto = new javax.swing.JLabel();
        tCodProducto = new javax.swing.JTextField();
        bBuscarPro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bNuevoPro = new javax.swing.JButton();
        bEditarPro = new javax.swing.JButton();
        bEliminarPro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lCedCliente = new javax.swing.JLabel();
        tCedCliente = new javax.swing.JTextField();
        bBuscarCli = new javax.swing.JButton();
        bNuevoCli = new javax.swing.JButton();
        bEditarCli = new javax.swing.JButton();
        bEliminarCli = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabCliente = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Fecha", "Cliente", "Total", "Estado", "Ver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabFactura);

        bBuscarFac.setText("Buscar");
        bBuscarFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarFacActionPerformed(evt);
            }
        });

        lNumFactura.setText("Número de Factura:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lNumFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBuscarFac)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(lNumFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNumFactura)
                    .addComponent(bBuscarFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestaFactura.addTab("Factura", jPanel1);

        tabProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabProducto);

        lCodProducto.setText("Código de Producto:");

        bBuscarPro.setText("Buscar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        bNuevoPro.setText("Nuevo");
        bNuevoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoProActionPerformed(evt);
            }
        });

        bEditarPro.setText("Editar");
        bEditarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarProActionPerformed(evt);
            }
        });

        bEliminarPro.setText("Eliminar");
        bEliminarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lCodProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tCodProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBuscarPro))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bEditarPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNuevoPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEliminarPro, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tCodProducto)
                                .addComponent(bBuscarPro))
                            .addComponent(lCodProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bNuevoPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEditarPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEliminarPro)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pestaFactura.addTab("Producto", jPanel2);

        lCedCliente.setText("Cédula de Cliente:");

        bBuscarCli.setText("Buscar");

        bNuevoCli.setText("Nuevo");
        bNuevoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoCliActionPerformed(evt);
            }
        });

        bEditarCli.setText("Editar");

        bEliminarCli.setText("Eliminar");
        bEliminarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarCliActionPerformed(evt);
            }
        });

        tabCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Celular", "Correo", "Direccion", "Tarjeta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabCliente);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(bNuevoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bEditarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lCedCliente)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tCedCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bBuscarCli)
                    .addGap(143, 143, 143)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bNuevoCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEditarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEliminarCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCedCliente)
                            .addComponent(bBuscarCli))
                        .addComponent(lCedCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        pestaFactura.addTab("Cliente", jPanel4);

        jMenu1.setText("Ajustes");

        jMenuItem1.setText("Administrar contraseña");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pestaFactura)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pestaFactura))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing


    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (cambioContrasenia == null || cambioContrasenia.isVisible() == false) {
            cambioContrasenia = new CambioContrasenia(claveAdmin);
            cambioContrasenia.setVisible(true);
            cambioContrasenia.toFront();
        } else {
            cambioContrasenia.toFront();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void bNuevoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoProActionPerformed
        // TODO add your handling code here:
        llenarDatosProducto();
    }//GEN-LAST:event_bNuevoProActionPerformed

    private void bBuscarFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarFacActionPerformed
        // TODO add your handling code here:
        try {
            Factura factura = controladorFactura.read(Integer.parseInt(tNumFactura.getText()));
            DetallesFactura detallesFactura = new DetallesFactura(factura);
            detallesFactura.setVisible(true);
        } catch (PSQLException ex) {
            JOptionPane.showMessageDialog(null, "La factura no existe");
        }
    }//GEN-LAST:event_bBuscarFacActionPerformed

    private void tabFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFacturaMouseClicked
        // TODO add your handling code here:
        try {
            int columna = tabFactura.getColumnModel().getColumnIndexAtX(evt.getX());
            int fila = evt.getY() / tabFactura.getRowHeight();

            if (fila < tabFactura.getRowCount() && fila >= 0 && columna < tabFactura.getColumnCount() && columna >= 0) {
                Object value = tabFactura.getValueAt(fila, columna);
                if (value instanceof JButton) {
                    ((JButton) value).doClick();
                    JButton boton = (JButton) value;
                    int numFactura = (evt.getY() / tabFactura.getRowHeight()) + 1;
                    try {
                        Factura factura = controladorFactura.read(numFactura);
                        DetallesFactura detallesFactura = new DetallesFactura(factura);
                        detallesFactura.setVisible(true);
                    } catch (PSQLException ex) {
                        Logger.getLogger(VistaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (java.lang.IndexOutOfBoundsException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tabFacturaMouseClicked

    private void bNuevoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoCliActionPerformed
        // TODO add your handling code here:
        int fila = tabCliente.getSelectedRow();
        try {
            Cliente cliente = controladorCliente.findByCedula((String) tabCliente.getValueAt(fila, 0));
            
        } catch (PSQLException ex) {
            Logger.getLogger(VistaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bNuevoCliActionPerformed

    private void bEliminarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarProActionPerformed
        // TODO add your handling code here:
        int fila = tabProducto.getSelectedRow();
        try {
            controladorProducto.delete((int) tabProducto.getValueAt(fila, 0));
        } catch (PSQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(VistaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        llenarDatosProducto();
    }//GEN-LAST:event_bEliminarProActionPerformed

    private void bEditarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarProActionPerformed
        // TODO add your handling code here:
        llenarDatosProducto();
    }//GEN-LAST:event_bEditarProActionPerformed

    private void bEliminarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarCliActionPerformed
        // TODO add your handling code here:
        int fila = tabCliente.getSelectedRow();
        try {
            controladorCliente.delete((String) tabCliente.getValueAt(fila, 0));
        } catch (PSQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(VistaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        llenarDatosCliente();
    }//GEN-LAST:event_bEliminarCliActionPerformed

    public void vaciarTablaProducto(DefaultTableModel modelo){
        int filas=tabProducto.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
    }
    
    public void vaciarTablaFactura(DefaultTableModel modelo){
        int filas=tabFactura.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
    }
    
    public void vaciarTablaCliente(DefaultTableModel modelo){
        int filas=tabCliente.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarCli;
    private javax.swing.JButton bBuscarFac;
    private javax.swing.JButton bBuscarPro;
    private javax.swing.JButton bEditarCli;
    private javax.swing.JButton bEditarPro;
    private javax.swing.JButton bEliminarCli;
    private javax.swing.JButton bEliminarPro;
    private javax.swing.JButton bNuevoCli;
    private javax.swing.JButton bNuevoPro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lCedCliente;
    private javax.swing.JLabel lCodProducto;
    private javax.swing.JLabel lNumFactura;
    private javax.swing.JTabbedPane pestaFactura;
    private javax.swing.JTextField tCedCliente;
    private javax.swing.JTextField tCodProducto;
    private javax.swing.JTextField tNumFactura;
    private javax.swing.JTable tabCliente;
    public static javax.swing.JTable tabFactura;
    private javax.swing.JTable tabProducto;
    // End of variables declaration//GEN-END:variables

}
